#!/usr/bin/env bash
# Install nginx web server and server a simple page

# Update package list
apt-get update -y

# Install nginx
apt-get install -y nginx

# Ensure it running
service nginx start

# Write content to index.html
cat << EOF > /var/www/html/index.html 
Hello World!
EOF

service nginx restart

