#!/usr/bin/env bash
# This script configures a server running Ubuntu to redirect any request
# coming in at /redirect_me to another page.

# Install nginx
apt update -y
apt-get install -y nginx

# Write content to index.html
echo "Hello World!" > /var/www/html/index.html

config_file="/etc/nginx/sites-available/default"

# Backup the original configuration file
cp $config_file /etc/nginx/sites-available/default.bak

# Configure redirection
redirect_rule="\\\n\tlocation /redirect_me {\n\t\treturn 301 https://www.google.com;\n\t}"
sed -i "53i $redirect_rule" $config_file

# Restart nginx to apply the new configuration
service nginx restart
