#!/usr/bin/env bash
##
#   This script performs the following tasks on a server running Ubuntu:
#
#   1. Installs Nginx.
#   2. Configures the server to redirect any requests coming in at /redirect_me to another page.
#   3. Sets up a custom 404 error page.
#   4. Adds a custom Nginx response header.
##

# Install nginx
apt update -y
apt-get install -y nginx

# Write content to index.html
echo "Hello World!" > /var/www/html/index.html

config_file="/etc/nginx/sites-available/default"

# Backup the original configuration file
cp $config_file /etc/nginx/sites-available/default.bak


echo "Ceci n'est pas une page" > /var/www/html/404.html

# Get hostname
HOSTNAME=$(hostname)

printf %s "
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;

    # Add index.php to the list if you are using PHP
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        # First attempt to serve request as file, then
        # as directory, then fall back to displaying a 404.
        add_header X-Served-By \"$HOSTNAME\";
        try_files \$uri \$uri/ =404;
    }

    # Configure redirection
    location /redirect_me {
        return 301 https://www.google.com;
    }

    # Define custom 404 page
    error_page 404 /404.html;
}
" > $config_file
# Start nginx
service nginx restart
