#!/usr/bin/env bash
# This script addresses an issue where the Nginx service inside the Docker container was not starting automatically.
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
