#!/usr/bin/env bash
# This Bash script displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59

i=0
hours=12
minute=59
while [ "$i" -le "$hours" ]; do
    echo Hour: $i
    j=1
    while [ "$j" -le "$minute" ]; do
        echo $j
        ((j++))
    done
    ((i++))
done
