#!/usr/bin/env bash
# The Bash script displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed

FILES=$(ls -- *)
for i in $FILES; do
    echo "$i" | cut -d '-' -f 2-
done
