#!/usr/bin/env bash
# The Bash script configures an Ubuntu server with the below requirements.
#    localhost resolves to 127.0.0.2
#    facebook.com resolves to 8.8.8.8.

FILE=~/hosts.new
cp /etc/hosts $FILE
# resolving locahost to 127.0.0.2
sed -i 's/127.0.0.1[[:space:]]localhost/127.0.0.2\tlocalhost/g' $FILE

# facebook.com resolves to 8.8.8.8
sed -i '/^8.8.8.8[[:space:]]facebook.com/!{$s/$/\n8.8.8.8       facebook.com/;}' $FILE

# update the file
cp -f $FILE /etc/hosts

# delete the file
rm $FILE
